### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter_markdown#145]
Stacktrace: 
```dart
RangeError (index): Invalid value: Valid value range is empty: 0

The relevant error-causing widget was: 
  HtmlView file:///Users/thinkdigital/IdeaProjects/tavern/lib/screens/package_details/package_details_screen.dart:440:18
When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:147:60)
#1      MarkdownBuilder.visitElementAfter (package:flutter_markdown/src/builder.dart:237:40)
#2      Element.accept (package:markdown/src/ast.dart:51:15)
#3      Element.accept (package:markdown/src/ast.dart:48:17)
#4      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:139:12)
...
```
This is thrown when rendering the following code:
```markdown
Flutter Deep Link Navigation [#](#flutter-deep-link-navigation)
===============================================================

Provides an elegant abstraction for complete deep linking navigation in flutter.

Orchestrates a native flutter navigator in the background.

Getting Started [#](#getting-started)
-------------------------------------

Please refer to the examples folder.

Features [#](#features)
-----------------------

*   `DeepLinkNavigator` mirrors native `Navigator` interface, also accessible through context
*   `DeepLinkNavigator.navigateTo` navigates to _ANY_ route in the hierarchy
*   Doesn't interfere with native dialogs, selects, and popups
*   Custom mixins add provide custom logic on a deep link basis (see multiple\_base\_routes example)
*   Animates transitions between routes as if navigation was done natively
*   
*   TODO: enumarate others

Limitations [#](#limitations)
-----------------------------

*   Can't currently define arbitrarily deep navigation hierarchies (think Spotify)
*   Can't store separate persisted navigation states for a multi-base route application (think Instagram)
*   Can't type `DeepLinkDispatcher.value(_, value, __)` due to recursive nature of navigation hierarchy definition

What's left to do [#](#whats-left-to-do)
----------------------------------------

\[x\] Finish UI testing single base example \[x\] Animated transition for pushes \[x\] Custom mixins \[x\] Exception handling routes \[\] Push with completer \[x\] Advanced example with multiple base routes and custom mixins \[\] Navigation diagrams \[\] Finish UI testing multi base example \[\] Fully clean up code, tests, and documentation \[\] Publish dart package \[\] Unit test deep link navigator logic
```
Flutter Deep Link Navigation [#](#flutter-deep-link-navigation)
===============================================================

Provides an elegant abstraction for complete deep linking navigation in flutter.

Orchestrates a native flutter navigator in the background.

Getting Started [#](#getting-started)
-------------------------------------

Please refer to the examples folder.

Features [#](#features)
-----------------------

*   `DeepLinkNavigator` mirrors native `Navigator` interface, also accessible through context
*   `DeepLinkNavigator.navigateTo` navigates to _ANY_ route in the hierarchy
*   Doesn't interfere with native dialogs, selects, and popups
*   Custom mixins add provide custom logic on a deep link basis (see multiple\_base\_routes example)
*   Animates transitions between routes as if navigation was done natively
*   
*   TODO: enumarate others

Limitations [#](#limitations)
-----------------------------

*   Can't currently define arbitrarily deep navigation hierarchies (think Spotify)
*   Can't store separate persisted navigation states for a multi-base route application (think Instagram)
*   Can't type `DeepLinkDispatcher.value(_, value, __)` due to recursive nature of navigation hierarchy definition

What's left to do [#](#whats-left-to-do)
----------------------------------------

\[x\] Finish UI testing single base example \[x\] Animated transition for pushes \[x\] Custom mixins \[x\] Exception handling routes \[\] Push with completer \[x\] Advanced example with multiple base routes and custom mixins \[\] Navigation diagrams \[\] Finish UI testing multi base example \[\] Fully clean up code, tests, and documentation \[\] Publish dart package \[\] Unit test deep link navigator logic

**Comment by KagurazakaHanabi** [comment]
I can't reproduce it

![Screenshot_2019-11-14-07-39-39](https://user-images.githubusercontent.com/23377765/68813915-4c2a3000-06b2-11ea-8c0c-bf6a6d0b3a04.png)

**Comment by ThinkDigitalSoftware** [comment]
I ran it again and I got it. I'll paste my file and see if you get the same results.
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-13 at 17 22 36](https://user-images.githubusercontent.com/23037821/68818585-4bee4e00-063a-11ea-8517-1c5c31e75fa1.png)

```dart
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(
        title: "Flutter Markdown Example",
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, @required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Expanded(
              child: Markdown(
                styleSheet: MarkdownStyleSheet.fromTheme(Theme.of(context))
                    .copyWith(
                        blockquote: TextStyle(
                            color: Colors.red), // this text should be red.
                        blockquoteDecoration: BoxDecoration(
                          color: Colors.yellow,
                          borderRadius: BorderRadius.circular(2.0),
                        )),
                data: """
                Flutter Deep Link Navigation [#](#flutter-deep-link-navigation)
===============================================================

Provides an elegant abstraction for complete deep linking navigation in flutter.

Orchestrates a native flutter navigator in the background.

Getting Started [#](#getting-started)
-------------------------------------

Please refer to the examples folder.

Features [#](#features)
-----------------------

*   `DeepLinkNavigator` mirrors native `Navigator` interface, also accessible through context
*   `DeepLinkNavigator.navigateTo` navigates to _ANY_ route in the hierarchy
*   Doesn't interfere with native dialogs, selects, and popups
*   Custom mixins add provide custom logic on a deep link basis (see multiple\_base\_routes example)
*   Animates transitions between routes as if navigation was done natively
*   
*   TODO: enumarate others

Limitations [#](#limitations)
-----------------------------

*   Can't currently define arbitrarily deep navigation hierarchies (think Spotify)
*   Can't store separate persisted navigation states for a multi-base route application (think Instagram)
*   Can't type `DeepLinkDispatcher.value(_, value, __)` due to recursive nature of navigation hierarchy definition

What's left to do [#](#whats-left-to-do)
----------------------------------------

\[x\] Finish UI testing single base example \[x\] Animated transition for pushes \[x\] Custom mixins \[x\] Exception handling routes \[\] Push with completer \[x\] Advanced example with multiple base routes and custom mixins \[\] Navigation diagrams \[\] Finish UI testing multi base example \[\] Fully clean up code, tests, and documentation \[\] Publish dart package \[\] Unit test deep link navigator logic
""",
              ),
            )
          ],
        ),
      ),
    );
  }
}

```

**Comment by KagurazakaHanabi** [comment]
Also can’t reproduce
I’m using [KagurazakaHanabi/flutter_markdown](https://github.com/KagurazakaHanabi/flutter_markdown) branch `Hanabi-patch-1`

**Comment by ThinkDigitalSoftware** [comment]
OK, I'm using 
```yaml 
flutter_markdown: ^0.3.0
```
and  Flutter (Channel master, v1.10.17-pre.58, on Mac OS X 10.15.2 19C39d, locale en-US)

**Comment by KagurazakaHanabi** [comment]
It’s fixed in https://github.com/flutter/flutter_markdown/commit/7db5fdb207525d8aea0a278b7e23712d434c3db9

**Comment by ThinkDigitalSoftware** [comment]
Thank you!

**Comment by ThinkDigitalSoftware** [comment]
Wait. It says that was committed 21 says ago. And so was v3.0. How does that work?

**Comment by KagurazakaHanabi** [comment]
It’s merged 19 days ago, but it seems not published to pub
```yaml
flutter_markdown:
  git: https://github.com/flutter/flutter_markdown.git
```

**Comment by ThinkDigitalSoftware** [comment]
Ah, ok. Thank you. I wish they would update pub everytime something gets merged into master. Thank you!

**Comment by talhashahab786** [comment]
You are not getting the data. The data folder from or data source is missing. The same happened for me. Later, I created the json file for data and pointed to that location. And it got fixed simply!
