### ISSUE TITLE
Adding an image into the demo text results in 'The getter 'iterator' was called on null.' exception. 

### ISSUE THREAD

**Issue by kostaa** [flutter/flutter_markdown#3]
I have added an image tag into the demo text: 
## Image
![Wikipedia](http://upload.wikimedia.org/wikipedia/commons/5/5a/Wikipedia-logo-v2-fr.png)

![image](https://user-images.githubusercontent.com/7585117/27307247-b4cf7df2-5540-11e7-86f2-04e81c1e04d8.png)

Got the following exception:

```
Launching example\demo.dart on Android SDK built for x86 in debug mode...
Built build\app/outputs/apk/app-debug.apk (21.7MB).
I/flutter (12596): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12596): The following NoSuchMethodError was thrown building LayoutId([<_ScaffoldSlot.body>]; id:
I/flutter (12596): _ScaffoldSlot.body):
I/flutter (12596): The getter 'iterator' was called on null.
I/flutter (12596): Receiver: null
I/flutter (12596): Tried calling: iterator
I/flutter (12596): 
I/flutter (12596): When the exception was thrown, this was the stack:
I/flutter (12596): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
I/flutter (12596): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
I/flutter (12596): #2      Element.accept (package:markdown/src/ast.dart:48)
I/flutter (12596): #3      Element.accept (package:markdown/src/ast.dart:48)
I/flutter (12596): #4      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:90)
I/flutter (12596): #5      _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:107)
I/flutter (12596): #6      _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:80)
I/flutter (12596): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3507)
I/flutter (12596): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #15     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3685)
I/flutter (12596): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #17     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4438)
I/flutter (12596): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #29     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (12596): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (12596): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (12596): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (12596): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (12596): #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #74     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (12596): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #80     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #81     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #90     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (12596): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #93     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (12596): #94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #99     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (12596): #100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #105    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #106    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #109    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (12596): #110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #112    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (12596): #113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #116    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #117    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #118    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #121    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (12596): #122    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #126    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #127    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (12596): #128    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #134    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (12596): #135    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #136    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #140    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #141    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (12596): #142    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #144    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4438)
I/flutter (12596): #145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #147    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:491)
I/flutter (12596): #148    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #151    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #152    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #153    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (12596): #154    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #155    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #159    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #160    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #161    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #162    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #163    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (12596): #164    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #165    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #167    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #168    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #169    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (12596): #170    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #171    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #172    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #173    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (12596): #174    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #175    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #176    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (12596): #177    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #178    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #180    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #181    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #182    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (12596): #183    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #184    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #185    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #187    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #188    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #189    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #190    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #191    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #193    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #194    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #195    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #196    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #197    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/Choreographer(12596): Skipped 58 frames!  The application may be doing too much work on its main thread.
I/flutter (12596): #198    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #199    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #200    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #201    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #202    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #203    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #205    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #206    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #207    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #208    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #209    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #210    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333)
I/flutter (12596): #211    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #212    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #214    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #215    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #216    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #217    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #218    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #220    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #221    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #222    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #223    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #224    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #226    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #227    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #228    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (12596): #229    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #230    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #231    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #233    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #234    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #235    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #236    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #237    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #238    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #239    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #240    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #241    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #242    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #243    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #244    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #245    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #246    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #247    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #248    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #249    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #250    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #251    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #252    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #253    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (12596): #254    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #255    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #256    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #257    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #258    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #259    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #260    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #261    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #262    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #263    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3403)
I/flutter (12596): #264    Element.rebuild (package:flutter/src/widgets/framework.dart:3292)
I/flutter (12596): #265    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371)
I/flutter (12596): #266    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3509)
I/flutter (12596): #267    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366)
I/flutter (12596): #268    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750)
I/flutter (12596): #269    Element.updateChild (package:flutter/src/widgets/framework.dart:2553)
I/flutter (12596): #270    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:732)
I/flutter (12596): #271    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:703)
I/flutter (12596): #272    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:649)
I/flutter (12596): #273    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2122)
I/flutter (12596): #274    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:648)
I/flutter (12596): #275    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:543)
I/flutter (12596): #276    runApp (package:flutter/src/widgets/binding.dart:581)
I/flutter (12596): #277    main (file:///D:/repo__dart_flutter/flutter_markdown/example/demo.dart:32)
I/flutter (12596): #278    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
I/flutter (12596): #279    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
I/flutter (12596): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by dwaindibbly** [comment]
I, too, have gotten this error

**Comment by kostaa** [comment]
Any news on this? Looks like there is a pull reqest to fix this issue.

**Comment by mit-mit** [comment]
Repro steps:

1. `flutter create markdowntest`
1. Add `flutter_markdown` to `pubspec.yaml`
1. Replace `main.dart` with:

```
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text('Markdown test'),
        ),
        body: new Markdown(data: _data),
      ),
    );
  }
}

const String _data = '''
# Welcome to Mallorca
  
There are many, many things to do in Mallorca.

![Sattelite picture of Mallorca](https://upload.wikimedia.org/wikipedia/commons/2/24/Mallorca.jpg"Mallorca")

You can:

* Fish
* Hike
* Ride a bike

''';
```

**Comment by mit-mit** [comment]
Attempting fix for this in https://github.com/dart-lang/markdown/pull/182
